# Generated by Django 5.1.5 on 2025-02-03 23:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="members",
            field=models.ManyToManyField(
                blank=True, related_name="room_members", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
